// Bangkok 2026 — Spots (aus Jans recherchierter Karte, 34 Ziele ab Hotel Oakwood Suites Tiwanon)
const HOTEL = {
  name: "Oakwood Suites Tiwanon", lat: 13.8387, lng: 100.5154,
  addr: "229 Krungthep-Nonthaburi Rd, Nonthaburi 11000",
  tel: "+6621499450",
  thai: "โอ๊ควูด สวีทส์ ทิวานนท์ — 229 ถนนกรุงเทพฯ-นนทบุรี บางเขน เมืองนนทบุรี 11000",
  gmaps: "https://www.google.com/maps/search/?api=1&query=Oakwood%20Suites%20Tiwanon%20Bangkok&query_place_id=ChIJRVowhVeb4jAR8Y4UPJncqx4"
};

const CATS = {
  tuer:   { label: "Vor der Tür", color: "#6BCB77" },
  stadt:  { label: "Stadt",       color: "#A78BFA" },
  luxus:  { label: "Luxus",       color: "#E8B04B" },
  party:  { label: "Party",       color: "#4FD8EB" },
  tattoo: { label: "Tattoo",      color: "#FF9950" },
  strand: { label: "Strand",      color: "#57A8FF" },
  tour:   { label: "Ausflüge",    color: "#F26D9E" }
};

function gm(q){ return "https://www.google.com/maps/search/?api=1&query=" + encodeURIComponent(q); }

const SPOTS = [
  // ————— VOR DER TÜR —————
  { cat:"tuer", name:"Jitmuangnon Muay Thai Gym", emoji:"🥊", lat:13.8340, lng:100.5120,
    bolt:"5 Min", fare:"60–80 ฿", hours:"Tägl. 6–19 Uhr", price:"Einzeltraining 500–800 ฿/Std.",
    desc:"Echtes Profi-Camp, 1 km vom Hotel — hier trainieren Rodtang & Panpayak. Ausländer dürfen mitmachen: Laufen, Seil, Pratzenrunden, Sandsack, Clinch.",
    tips:["Nachmittagseinheit ist die beste","Für dich beruflich wie privat der beste Programmpunkt der Liste"],
    warn:null, book:["Einfach hinlaufen oder vorher anrufen","Bar zahlen"], gmaps:gm("Jitmuangnon Muay Thai Gym Nonthaburi") },
  { cat:"tuer", name:"CampYard Bar", emoji:"🎸", lat:13.8320, lng:100.5200,
    bolt:"5 Min", fare:"60 ฿", hours:"Tägl. 17–24 Uhr",
    desc:"Retro-Bar mit Thai-Livemusik, 1 km vom Hotel. Stylisch, gute Stimmung — die seltene Bar in Nonthaburi.",
    tips:["Musik teils laut — nichts für lange Gespräche"], warn:null, book:[], gmaps:gm("CampYard Nonthaburi") },
  { cat:"tuer", name:"Highyena Home Bar", emoji:"🍺", lat:13.8450, lng:100.5050,
    bolt:"15 Min", fare:"80–100 ฿", hours:"Di–So ab 17, Fr/Sa bis 2 Uhr, Mo zu",
    desc:"4,8 ★ — elf Craft-Biere vom Fass, Holzofenpizza, Livemusik. Der Laden der Einheimischen.",
    tips:["Nur Bargeld & QR — keine Kreditkarte!"], warn:null, book:[], gmaps:gm("Highyena Home Bar Nonthaburi") },
  { cat:"tuer", name:"Owl Market (Nachtmarkt)", emoji:"🦉", lat:13.8600, lng:100.5150,
    bolt:"10 Min", fare:"70–90 ฿", hours:"Tägl. 17–24 Uhr",
    desc:"Riesiger Nachtmarkt, 4,4 ★ bei 15.700 Bewertungen. Streetfood + Secondhand-Klamotten ab 10 ฿.",
    tips:["Perfekt für den ersten lockeren Abend"], warn:"Gedränge = Handy nach vorn.", book:[], gmaps:gm("Owl Market Nonthaburi") },
  { cat:"tuer", name:"Wat Chaloem Phrakiat", emoji:"🛕", lat:13.8551, lng:100.4869,
    bolt:"12 Min", fare:"80–100 ฿", hours:"Tagsüber", price:"Eintritt frei",
    desc:"Der schönste Tempel der Gegend, direkt am Fluss, chinesisch beeinflusst, Pfauen auf dem Gelände. Fast keine Touristen.",
    tips:["Schultern & Knie bedeckt"], warn:null, book:[], gmaps:gm("Wat Chaloem Phra Kiat Worawihan Nonthaburi") },
  { cat:"tuer", name:"Ko Kret (Flussinsel)", emoji:"🚲", lat:13.9126, lng:100.4750,
    bolt:"20 Min + Boot", fare:"120–150 ฿", hours:"Am WE lebendig, unter der Woche fast leer", price:"Fahrrad 40 ฿/Tag, Fähre paar Baht",
    desc:"Autofreie Flussinsel der Mon-Minderheit. Töpferei, Streetfood, mit dem Rad einmal rum.",
    tips:["Sonntag = Markt-Tag, dann ist am meisten los"], warn:null, book:[], gmaps:gm("Ko Kret Nonthaburi") },
  { cat:"tuer", name:"Nonthaburi Pier (Expressboot)", emoji:"⛴️", lat:13.8420, lng:100.4930,
    bolt:"10 Min", fare:"70–90 ฿", price:"Boot in die Altstadt ~20 ฿",
    desc:"Nordende der Chao-Phraya-Expressboote. Für 20 Baht den Fluss runter bis zur Altstadt — die schönste Anreise, die Bangkok hat.",
    tips:["Orange Flagge = Standardlinie, alle paar Minuten","Kombi: Boot hin, abends Bolt zurück"], warn:null, book:[], gmaps:gm("Nonthaburi Pier") },
  { cat:"tuer", name:"Central Westgate (Mall)", emoji:"🛍️", lat:13.8766, lng:100.4113,
    bolt:"25 Min (nimm die Bahn!)", fare:"MRT 25 ฿ / 15 Min", hours:"Tägl. 10–22 Uhr",
    desc:"Riesige Mall, 4 Stationen mit der Purple Line. Kino, Foodcourt, Klamotten.",
    tips:["Einziger Ort, wo Bolt Unsinn ist: MRT 15 Min/25 ฿ schlägt Bolt 25 Min/200 ฿"], warn:null, book:[], gmaps:gm("Central WestGate Bang Yai") },
  { cat:"tuer", name:"Health Land Chaengwattana", emoji:"💆", lat:13.9050, lng:100.5250,
    bolt:"20 Min", fare:"120–160 ฿", hours:"Tägl., Walk-in unter der Woche meist ok", price:"2 Std. Thai-Massage ~650 ฿",
    desc:"Seriöse Massage-Kette, private Räume mit Dusche. Weltklasse-Massage für 15–20 €.",
    tips:["Nach dem Muay-Thai-Training Gold wert"], warn:null, book:["Walk-in oder online reservieren"], gmaps:gm("Health Land Chaengwattana") },
  { cat:"tuer", name:"T.S.R. Golf Driving Range", emoji:"⛳", lat:13.8450, lng:100.5300,
    bolt:"10 Min", fare:"70–90 ฿", price:"40 Bälle = 30 ฿",
    desc:"Driving Range um die Ecke. In Ulm zahlst du das Zehnfache.",
    tips:[], warn:null, book:[], gmaps:gm("TSR Golf Driving Range Nonthaburi") },

  // ————— STADT —————
  { cat:"stadt", name:"Chatuchak Weekend Market", emoji:"🧺", lat:13.7999, lng:100.5502,
    bolt:"25 Min", rush:"45 Min", fare:"180–240 ฿", mrt:"Purple → Tao Poon → Blue, ~30–35 Min", hours:"NUR Sa + So, Mo komplett zu",
    desc:"Einer der größten Märkte der Welt — 15.000 Stände. Klamotten, Kunst, Essen, alles.",
    tips:["Früh hin (vor 11), mittags wird's brutal voll & heiß","Feilschen ok: Startpreis −30–40 %"],
    warn:"Taschendiebe im Gedränge — Rucksack nach vorn, Wertsachen in die Fronttasche.", book:[], gmaps:gm("Chatuchak Weekend Market") },
  { cat:"stadt", name:"Grand Palace + Wat Pho", emoji:"👑", lat:13.7500, lng:100.4913,
    bolt:"35 Min", rush:"65 Min", fare:"230–300 ฿", mrt:"Blue Line bis Sanam Chai, ~50 Min · oder Expressboot ab Nonthaburi Pier", hours:"Nur bis 15:30!", price:"500 ฿ · Wat Pho 300 ฿",
    desc:"Der Königspalast + der liegende Buddha nebenan. Wat Pho hat die Massageschule des Landes — Massage direkt auf dem Tempelgelände.",
    tips:["MORGENS fahren — nachmittags Rushhour + um 15:30 ist zu","Schultern & Knie bedeckt, sonst kein Einlass","Schönste Anreise: Expressboot ab Nonthaburi Pier (20 ฿)"],
    warn:"„Der Palast ist heute geschlossen“-Masche der Tuk-Tuk-Fahrer davor: Er ist täglich offen. Einfach weitergehen.", book:["Ticket am offiziellen Schalter, 500 ฿, bar oder Karte"], gmaps:gm("The Grand Palace Bangkok") },
  { cat:"stadt", name:"Golden Mount (Wat Saket)", emoji:"🌅", lat:13.7539, lng:100.5065,
    bolt:"32 Min", rush:"60 Min", fare:"200–260 ฿", hours:"Tägl. ~7–19 Uhr", price:"~100 ฿",
    desc:"Vergoldeter Chedi auf 80-Meter-Hügel, 340 flache Stufen mit Glocken. Oben: 360°-Blick gratis auf Augenhöhe mit dem 900-฿-Mahanakhon.",
    tips:["16:30 Uhr = tiefe Sonne über der Altstadt","Perfekte Kombi: danach 5 Min rüber zum Rajadamnern-Stadion","Starke Foto-Location (Spiraltreppe!)"],
    warn:"Auch hier die „heute geschlossen“-Masche — Tempel ist täglich offen.", book:[], gmaps:gm("Wat Saket Golden Mount Bangkok") },
  { cat:"stadt", name:"Chinatown (Yaowarat)", emoji:"🏮", lat:13.7398, lng:100.5096,
    bolt:"38 Min", rush:"70 Min", fare:"220–290 ฿", mrt:"Blue Line bis Wat Mangkon — Ausgang mitten im Viertel", hours:"Ab 18:30, MONTAGS ZU (Garküchen)",
    desc:"Ab 18 Uhr Neon-Schlucht voller Garküchen: Riesengarnelen, Dim Sum, Entennudeln. Mehrere Stände mit Michelin Bib Gourmand. Mit 400 ฿ im Bauch isst du dich quer durch.",
    tips:["Die Stände mit den längsten Thai-Schlangen sind die richtigen","Wat Traimit: 5,5-Tonnen-Buddha aus massivem Gold","Zweitbeste Foto-Kulisse der Stadt (Neon bei Nacht)"],
    warn:"Gedränge = Taschendiebe, Handy nach vorn. Preis vor dem Bestellen fragen, wenn kein Schild. Edelstein-„Einladungen“: weitergehen.", book:[], gmaps:gm("Yaowarat Road Chinatown Bangkok") },
  { cat:"stadt", name:"Rajadamnern Muay Thai Stadion", emoji:"🏟️", lat:13.7590, lng:100.5063,
    bolt:"32 Min", rush:"60 Min", fare:"200–260 ฿", hours:"Kampfabende — Mi & So schon ab 17 Uhr", price:"Tickets ab ~700 ฿, Oberrang ~1.000 ฿ (teils Freibier inkl.)",
    desc:"Ältestes Muay-Thai-Stadion des Landes, 4,8 ★ bei 9.000+ Bewertungen. Stimmung elektrisch.",
    tips:["Kombi-Abend: 16:30 Golden Mount → 18:00 Kämpfe → 21:00 Chinatown","Tickets vorab online = kein Schlangestehen"],
    warn:"Tickets NUR über die offizielle Seite rajadamnern.com — nicht von Schleppern davor.", book:["rajadamnern.com öffnen","Kampfabend wählen, Oberrang reicht völlig","QR-Ticket aufs Handy"], gmaps:gm("Rajadamnern Stadium Bangkok"), site:"https://rajadamnern.com" },
  { cat:"stadt", name:"Terminal 21 + Pier-21-Foodcourt", emoji:"🍜", lat:13.7373, lng:100.5600,
    bolt:"35 Min", rush:"65 Min", fare:"230–300 ฿", mrt:"Blue Line bis Sukhumvit (Asok)", hours:"Tägl. 10–22 Uhr", price:"Gerichte ab 50 ฿",
    desc:"Mall mit Themen-Etagen — und im 5. Stock der Preis-Leistungs-König der Stadt: Garküchen-Qualität ab 50 Baht.",
    tips:["Perfekter Start für jeden Sukhumvit-Abend","Geldkarte am Foodcourt-Schalter aufladen, Rest zurücktauschen"], warn:null, book:[], gmaps:gm("Terminal 21 Asok Bangkok") },
  { cat:"stadt", name:"Jodd Fairs Ratchada (Nachtmarkt)", emoji:"🌃", lat:13.7581, lng:100.5687,
    bolt:"30 Min", fare:"200–260 ฿", hours:"Tägl. 16–1 Uhr",
    desc:"Der beste Nachtmarkt Bangkoks — 700+ Stände, Essen, Klamotten, Live-Musik. Gut alleine zu machen.",
    tips:["Leng Saab (Schweine-Rückgrat-Turm) ist DAS Foto-Gericht"], warn:null, book:[], gmaps:gm("Jodd Fairs Rama 9") },
  { cat:"stadt", name:"Klong-Tour im Longtail (Thonburi)", emoji:"🛶", lat:13.7437, lng:100.4889,
    bolt:"35 Min", fare:"230–300 ฿", price:"Privatboot 1.500–2.500 ฿",
    desc:"Privates Longtail-Boot durch die Kanäle von Thonburi bei Sonnenaufgang. Um 7 Uhr früh gehört dir die Stadt allein.",
    tips:["Start ab Sathorn/Oriental Pier oder Wat Arun","Preis + Dauer VOR dem Einsteigen festmachen"],
    warn:"Nur an offiziellen Piers buchen — nicht bei Anquatschern am Straßenrand.", book:["Am Pier: Route zeigen lassen","1 Std. = fair bei 1.000–1.500 ฿"], gmaps:gm("Wat Arun Bangkok") },
  { cat:"stadt", name:"Bang Krachao (grüne Lunge)", emoji:"🌿", lat:13.6784, lng:100.5620,
    bolt:"45 Min + Boot", fare:"300–380 ฿", price:"Fahrrad ~100 ฿, Boot 10 ฿",
    desc:"Flussschleife voller Dschungel und Holzstege mitten in der Stadt. Halber Tag Radfahren, kostet fast nichts.",
    tips:["Früh los — mittags brütend heiß"], warn:null, book:[], gmaps:gm("Bang Krachao Bangkok") },
  { cat:"tour", name:"Ayutthaya — selbst per Zug", emoji:"🏛️", lat:14.3532, lng:100.5689,
    bolt:"Zug 1:15 Std. ab Krung Thep Aphiwat", fare:"Zug nur 30–50 ฿ (Promo bis 31.10.26)", hours:"Ruinen tägl. 8–18 Uhr · Zug z. B. 9:05 → 10:20 an", price:"Selbst ~600 ฿ komplett — GYG-Tour kostet 29–37 €",
    desc:"Alte Königsstadt: Tempelruinen zum Reinlaufen, beeindruckender als der Grand Palace, ein Bruchteil der Touristen. NEU seit 01.08.2026: Direktzug ab Krung Thep Aphiwat (Bang Sue) — MRT-Anschluss von deinem Hotel.",
    tips:["Rechnung: Zug ~100 ฿ hin+zurück, Roller 250 ฿, Sammelticket 220 ฿ = ~15 € statt 30+ € Tour — und du bist frei","Ticket nur am Schalter (kein Online-Verkauf), Zug 9003 um 9:05 ist dein Slot","Wat Mahathat: Buddha-Kopf im Baum","Ayothaya Floating Market: reine Touri-Show — kannst du dranhängen, kein Muss"],
    warn:"Tuk-Tuk statt Roller? Pauschale VOR der Fahrt festmachen (4 Std. ~ 800–1.000 ฿).", book:["MRT bis Krung Thep Aphiwat (Bang Sue)","Schalter: Zug nach Ayutthaya, ~50 ฿","Vor Ort Roller/Tuk-Tuk, abends zurück"], gmaps:gm("Ayutthaya Historical Park") },
  { cat:"tour", name:"Bangkok Elephant Park (ethisch)", emoji:"🐘", lat:13.6880, lng:101.0600,
    bolt:"1,5–2 Std. mit Bolt", fare:"~900–1.300 ฿/Strecke", hours:"Halbtag OHNE Transfer: 9–12 oder 13–16:30 Uhr", price:"GYG ~43–55 € (Halbtag)",
    desc:"Ethische Elefantenpflege in Chachoengsao, 4,8 ★ (1.000+): füttern, Schlamm-Spa, baden — kein Reiten, keine Shows. Thai-Buffet inklusive. Dein Guide-frei-Trick: Die Option OHNE Transfer buchen und selbst mit Bolt hin — empfehlen sogar die Bewertungen.",
    tips:["Ohne-Transfer-Option = günstiger + du bestimmst das Tempo","Wechselklamotten + Handtuch mitnehmen (Schlammbad!)","Vormittags-Slot nehmen — nachmittags Regenzeit-Schauer"],
    warn:"Abgelegen: Für den Rückweg den Bolt-Fahrer warten lassen (Festpreis vereinbaren) oder notfalls doch die Transfer-Option nehmen — draußen fahren wenige Autos.",
    book:["GetYourGuide: „Bangkok Elephant Park“ → Halbtag ohne Transfer","Bis 24 h vorher kostenlos stornierbar"], site:"https://www.getyourguide.com/de-de/bangkok-l169/bangkok-ethische-elefanten-tour-mit-hoteltransfer-t740092/", gmaps:gm("Bangkok Elephant Park Chachoengsao") },
  { cat:"tour", name:"Damnoen Saduak + Maeklong Zugmarkt", emoji:"🚂", lat:13.5205, lng:99.9599,
    bolt:"Fahrer ~1,5 Std./Strecke", fare:"Tagesfahrer 2.500–3.500 ฿ (bis 4 Pers.)", hours:"FRÜH starten: ~7 Uhr am schwimmenden Markt · Maeklong-Zug ca. 8:30 & 11:10", price:"Selbst deutlich unter dem Tour-Preis",
    desc:"Der Klassiker-Doppelpack: schwimmender Markt in Damnoen Saduak + der Markt, der auf Zuggleisen steht — bei Durchfahrt klappen alle Stände in Sekunden weg. Als Halbtag machbar, wenn du früh los bist.",
    tips:["Beste Kombi: 6 Uhr los → Damnoen Saduak vor den Bussen → 11:10-Zugdurchfahrt in Maeklong","Boot: shared ist okay und billig, privat ~2.000 ฿/Boot — Preis IMMER vorher fix","Zugzeiten verschieben sich gern — vor Ort nochmal checken"],
    warn:"Abzock-Klassiker Nr. 1: Nicht das erste Boot am Straßenrand nehmen, nie „Ticket-Büros“ auf dem Weg — erst am offiziellen Pier schauen.",
    book:["Ohne Gruppe: privater Tagesfahrer über Klook/Hotel, beide Stopps + Endpreis schriftlich","Hardcore-DIY: Minivan ab Southern Bus Terminal ab ~100 ฿"], gmaps:gm("Damnoen Saduak Floating Market") },
  { cat:"tour", name:"Chao-Phraya Dinner-Cruise (5 Sterne)", emoji:"🛳️", lat:13.7045, lng:100.5028,
    bolt:"40 Min bis Asiatique", fare:"260–340 ฿", hours:"Tägl., Slots ab 18 Uhr, Hauptfahrt 20–22 Uhr, Check-in ~19:45", price:"ab ~26 € · mit Dinner 34–52 €",
    desc:"Die neueste Luxus-Cruise auf dem Fluss: ab Asiatique The Riverfront vorbei an ICONSIAM, Wat Arun und Grand Palace im Nachtlicht. Braucht keinen Guide — ist eh nur ein Ticket: buchen, hingehen, einsteigen.",
    tips:["18-Uhr-Slot = Sonnenuntergang + Nachtlichter in einem","Als Solo top: Deck-Platz statt Tisch, Kamera mitnehmen","Kombinierbar: vorher Asiatique-Nachtmarkt, danach Bolt heim"],
    warn:"Nur online mit Datum/Slot buchen — Ticketverkäufer am Pier-Vorplatz sind teurer oder falsch.",
    book:["GetYourGuide: Datum + Uhrzeit wählen","QR-Ticket aufs Handy, Check-in Asiatique Pier"], site:"https://www.getyourguide.com/de-de/bangkok-l169/bangkok-die-neueste-luxuriose-5-sterne-kreuzfahrt-auf-dem-chao-phraya-in-bangkok-t960991/", gmaps:gm("Asiatique The Riverfront Bangkok") },
  { cat:"stadt", name:"Mahanakhon SkyWalk", emoji:"🏙️", lat:13.7233, lng:100.5285,
    bolt:"38 Min", fare:"250–320 ฿", hours:"Tägl. 10–24 Uhr", price:"~900 ฿ (online günstiger)",
    desc:"Glasboden in 314 m Höhe. Beeindruckend — aber Golden Mount liefert den Altstadt-Blick gratis.",
    tips:["Wenn, dann zum Sonnenuntergang mit Online-Zeitfenster-Ticket"],
    warn:"Tickets nur über die offizielle Seite oder Klook — Zeitfenster wählen.", book:[], gmaps:gm("King Power Mahanakhon Bangkok") },

  // ————— LUXUS & ABEND —————
  { cat:"luxus", name:"Oriental Spa (Mandarin Oriental)", emoji:"🧖", lat:13.7237, lng:100.5147,
    bolt:"40–45 Min", fare:"250–330 ฿", price:"Moringa 2 Std. = 6.900 ฿ + 17 % (~211 €)", hours:"DEIN TERMIN: So 30.08., 10:30 Uhr ✓",
    desc:"GEBUCHT! Bis 60 Min vorher ankommen: Sauna, Dampfbad & Jacuzzi im Wellness Centre sind inklusive. Bestätigungs-Nr. in Meine Reisedaten.",
    tips:["DEIN WEG: Bolt zum Mandarin Oriental Hotel (Stadtseite) → gratis Hotelboot ab Hotel-Pier über den Fluss zum Spa","Beim Boot einfach sagen: „Oriental Spa, appointment 10:30“","Danach: ICONSIAM nur 750 m zu Fuß","Storno nur bis 24 h vorher — sonst 100 % fällig","Payment-Link kommt 2 Tage vorher per Mail (28.08.)"],
    warn:null, book:["mandarinoriental.com/bangkok → Spa → Termin buchen"], gmaps:gm("Mandarin Oriental Bangkok Hotel") },
  { cat:"luxus", name:"Gaggan Anand (Restaurant)", emoji:"🍽️", lat:13.7397, lng:100.5450,
    bolt:"38 Min", fare:"250–320 ฿", hours:"Di + Mi ZU — Wochen vorher buchen!", price:"Tasting-Menü, gehobene Preisklasse",
    desc:"Eines der besten Restaurants Asiens. Der Chef steht 4 Stunden selbst im Raum — Stand-up-Comedy trifft Menü, Handys aus. Perfekt für Alleinreisende: Das Erlebnis ersetzt das Tischgespräch.",
    tips:["Tresenplätze für Solo-Gäste oft kurzfristig frei"],
    warn:null, book:["gaggananand.com → Reservierung → einzelner Sitzplatz"], gmaps:gm("Gaggan Anand Bangkok") },
  { cat:"luxus", name:"Sky Bar (Lebua) — 1 Drink & Foto", emoji:"🥂", lat:13.7218, lng:100.5164,
    bolt:"40 Min", fare:"250–330 ฿", hours:"Ab 17 Uhr — Dresscode!", price:"Cocktail ~40 €",
    desc:"Der Hangover-2-Rooftop. Aussicht top, Preise Touristenfalle. Einmal hin, ein Drink, Foto, weiter.",
    tips:["Danach besser: Octave oder Vesper","Lange Hose + geschlossene Schuhe Pflicht"], warn:null, book:[], gmaps:gm("Sky Bar Lebua Bangkok") },
  { cat:"luxus", name:"Octave Rooftop (Thonglor)", emoji:"🌆", lat:13.7247, lng:100.5827,
    bolt:"45 Min", fare:"280–360 ฿", hours:"17–2 Uhr", price:"Mindestverzehr ~1.800 ฿",
    desc:"Das bessere Rooftop: 360°, DJ, entspannter als Sky Bar. Auf dem Marriott Thonglor.",
    tips:["Zum Sonnenuntergang kommen, oben anfangen"], warn:null, book:[], gmaps:gm("Octave Rooftop Lounge Bangkok") },
  { cat:"luxus", name:"Vesper & Rabbit Hole (Bars)", emoji:"🍸", lat:13.7268, lng:100.5348,
    bolt:"38 Min", fare:"250–320 ฿", hours:"Ab ~18 Uhr",
    desc:"Zwei der besten Cocktailbars Asiens. Setz dich an den TRESEN, nicht an den Tisch — so kommst du automatisch ins Gespräch.",
    tips:["Vesper: Silom · Rabbit Hole: Thonglor — je nach Abend-Route"], warn:null, book:[], gmaps:gm("Vesper Cocktail Bar Bangkok") },
  { cat:"luxus", name:"Saxophone Pub (Livejazz)", emoji:"🎷", lat:13.7629, lng:100.5372,
    bolt:"28 Min", fare:"180–240 ฿", hours:"Tägl. abends, Musik ab ~20:30",
    desc:"Livejazz & Blues seit den Achtzigern am Victory Monument. Gemischtes Publikum, Tresen-Atmosphäre — da will keiner was von dir.",
    tips:["Guter „entspannter Abend“-Joker"], warn:null, book:[], gmaps:gm("Saxophone Pub Bangkok") },
  { cat:"luxus", name:"Maßanzug in Silom", emoji:"🤵", lat:13.7280, lng:100.5340,
    bolt:"38 Min", fare:"250–320 ฿", price:"Vollmaß ab 300–500 €, fertig in 3–4 Tagen",
    desc:"Gute Schneider liefern in 3–4 Tagen. Früh in der Reise bestellen, 2 Anproben einplanen.",
    tips:["Stoff & Preis schriftlich, Anzahlung max. 50 %"],
    warn:"Finger weg von Läden, zu denen dich ein Tuk-Tuk-Fahrer bringt — das ist IMMER Provision.", book:[], gmaps:gm("tailor Silom Bangkok") },
  { cat:"luxus", name:"Foto-Shooting Golden Hour", emoji:"📸", lat:13.7437, lng:100.4895,
    bolt:"je nach Location", fare:"—", price:"~150 € für 2 Std. / 30 bearbeitete Bilder",
    desc:"The Photo Experience & Co. — maßgeschneidert, auch für Solo-Reisende. Beste Kulissen: Wat Arun zur Golden Hour, Chinatown-Neon nach Einbruch der Dunkelheit, Rooftop.",
    tips:["Fotograf ANS Hotel bestellen (Rooftop/Pool), nicht ins Zimmer","Anzahl bearbeiteter Bilder schriftlich"],
    warn:"Nur über Plattform buchen (TripAdvisor/Localgrapher) — keine Vorkasse an Instagram-Profile.", book:["TripAdvisor: „The Photo Experience Bangkok“","2 Std. Golden Hour buchen, Location abstimmen"], gmaps:gm("Wat Arun Bangkok") },

  // ————— PARTY & CLUBS —————
  { cat:"party", name:"Sukhumvit Soi 11", emoji:"🍹", lat:13.7415, lng:100.5555,
    bolt:"35 Min", rush:"70 Min", fare:"230–300 ฿",
    desc:"Die kompakteste Ausgehstraße: 800 m Bars, Rooftops, Streetfood. Highlight: Havana Social — Speakeasy mit Eingang durch eine Telefonzelle.",
    tips:["Dein Tattoo-Studio ink.inc liegt in derselben Straße","Ab hier 10 Min Bolt nach Thonglor"],
    warn:"Je kleiner die Soi-Nummer, desto mehr will dir jemand was verkaufen. Nie mitgehen, wenn dich jemand „mitnimmt“ — Provisions-Masche.", book:[], gmaps:gm("Sukhumvit Soi 11 Bangkok") },
  { cat:"party", name:"Beam (Thonglor)", emoji:"🔊", lat:13.7333, lng:100.5817,
    bolt:"45 Min", rush:"80 Min", fare:"280–360 ฿", hours:"Ab 23 Uhr, Fr/Sa die Nächte", price:"Eintritt 600–1.200 ฿ · Bier ~250 ฿",
    desc:"Für Leute, die wegen der Musik kommen: House/Techno, kinetischer Tanzboden, VOID-Soundsystem. Kein Flaschen-Posing.",
    tips:["GESCHLOSSENE Schuhe — wird erst an der Tür gesagt","Buckets sind zu 80 % Eis — lieber Bier","Reisepass im Original mitnehmen (vordere Tasche)"],
    warn:"Rückweg um 3 Uhr: Bolt aus dem Club bestellen, 400–600 ฿ Nachtzuschlag einplanen.", book:[], gmaps:gm("Beam Club Thonglor Bangkok") },
  { cat:"party", name:"Route 66 + Onyx (RCA)", emoji:"🎉", lat:13.7509, lng:100.5751,
    bolt:"40 Min", fare:"250–330 ฿", hours:"Ab ~22 Uhr", price:"Eintritt 300–500 ฿ inkl. 1–2 Drinks · Bier ~100 ฿",
    desc:"Route 66: Mega-Club, mehrere Räume, Studenten & Expats, Preis-Leistung unschlagbar. Onyx nebenan: EDM, LED-Wände, Festival-Produktion. Man wechselt an einem Abend zwischen beiden.",
    tips:["Route 66 = viele Tische, wenig Tanzfläche. Tanzen → Onyx","Dresscode: keine Flip-Flops/Shorts/Tanktops"],
    warn:"Reisepass im Original wird bei Ausländern oft verlangt.", book:[], gmaps:gm("Route 66 Club RCA Bangkok") },
  { cat:"party", name:"Sing Sing Theater", emoji:"🎭", lat:13.7307, lng:100.5769,
    bolt:"45 Min", fare:"280–360 ฿", hours:"Ab 21 Uhr, Mo zu",
    desc:"Asiatisch-opulent, theatralisch, House & Techno — der Laden, den du fotografierst. Erwachsener als RCA.",
    tips:["Hemd mit Kragen = sichere Wahl"], warn:null, book:[], gmaps:gm("Sing Sing Theater Bangkok") },
  
  
  // ————— TATTOO —————
  { cat:"tattoo", name:"ink.inc Tattoo (Sukhumvit 11)", emoji:"🖋️", lat:13.7420, lng:100.5560,
    bolt:"35 Min", fare:"230–300 ฿", hours:"Tägl. 11–22 Uhr",
    desc:"5,0 ★ bei 6.100+ Bewertungen — stärkste Bilanz der Stadt. Drei Etagen, modern, sehr sauber.",
    tips:["JETZT per Instagram/WhatsApp anschreiben — gute Artists sind Wochen ausgebucht","Zielfenster: 4./5.09. (nach Strand & Pool!)","Festpreis fürs Motiv nennen lassen, nicht Stundensatz"],
    warn:"Nadel muss VOR deinen Augen aus versiegelter Packung kommen — sonst aufstehen und gehen.", book:["Instagram @ink.inc.tattoo anschreiben","Motiv + Termin 4./5.09. anfragen","Anzahlung 1.000–3.000 ฿ normal"], gmaps:gm("ink.inc tattoo Bangkok Sukhumvit 11") },
  { cat:"tattoo", name:"All Day Tattoo (Sukhumvit 47)", emoji:"✒️", lat:13.7288, lng:100.5732,
    bolt:"40 Min", fare:"250–330 ฿", hours:"Tägl. 12–20 Uhr",
    desc:"4,9 ★ (2.841) — eigenes Design-Team führt dich durch den Entwurf, alle sprechen fließend Englisch.",
    tips:["Gut für größere/komplexere Motive mit Beratung"], warn:"Gleiche Nadel-Regel wie überall.", book:["alldaytattoo.com → Booking-Formular"], gmaps:gm("All Day Tattoo Bangkok") },
  { cat:"tattoo", name:"PUREink (Silom)", emoji:"🪡", lat:13.7260, lng:100.5230,
    bolt:"38 Min", fare:"250–320 ฿", hours:"Tägl. 9–23:30 — flexibelstes Zeitfenster",
    desc:"5,0 ★ (2.021). Buchung per WhatsApp, After-Care-Kit inklusive.",
    tips:["Preise: klein 2.000–5.000 ฿ · Stunde 2.500–5.000 ฿ · halber Arm 15.000–35.000 ฿"],
    warn:"KEINE Buddha-Motive — gilt in Thailand als respektlos, kann Einreiseprobleme geben.", book:["WhatsApp über pureink-bangkok.com"], gmaps:gm("PUREink Tattoo Silom Bangkok") },

  // ————— STRAND & INSELN —————
  { cat:"strand", name:"Koh Larn — Samae Beach", emoji:"🏝️", lat:12.9165, lng:100.7743,
    bolt:"Fahrer 2,5 Std. · Bus+Fähre 4 Std.", fare:"Fahrer 2.500–3.500 ฿/Tag · Fähre 30 ฿", hours:"Früh los! Letzte Fähre zurück ~17–18 Uhr",
    desc:"Die einzige Postkarte in Tagestrip-Reichweite: weißer Sand, klares Wasser. Samae = bester Kompromiss (4,5 ★, 7.000+ Bewertungen). Ta Yai = ruhig, Tawaen = voll (Anleger), Nual = Affen in den Felsen.",
    tips:["Privater Ganztagsfahrer über Klook/Hotel — schriftlich: Ziele + Endpreis","Roller auf der Insel 200–400 ฿ — VORHER Fotos vom Zustand machen","Sammeltaxi Pier→Samae 30–40 ฿","Liege 100 ฿, Dusche 50 ฿"],
    warn:"Ehrliche Rechnung: ~5 Std. Fahrt für ~4 Std. Strand — nur machen, wenn dir das den Tag wert ist (steht deshalb NICHT im Plan). NIEMALS den Reisepass als Pfand für den Roller. Regenzeit: Quallen möglich — auf Warnschilder & Essigstationen achten.", book:["Bali Hai Pier Pattaya → Fähre 30 ฿ (45 Min) oder Speedboot ab 150 ฿"], gmaps:gm("Samae Beach Koh Larn") },
  
  { cat:"strand", name:"Suvarnabhumi Airport (BKK)", emoji:"✈️", lat:13.6900, lng:100.7501,
    bolt:"45–60 Min", fare:"~600 ฿ + Maut", hours:"Rückflug 6.9.: 22:55 Uhr — 3 Std. vorher da sein",
    desc:"Dein Flughafen. Ankunft 28.8. um 13:45: TDAC-QR + Pass bereithalten, 20–40 Min Immigration, Gepäck, raus.",
    tips:["Transfer ist in deiner Buchung INKLUSIVE — Abholzeit 24 h vorher in „Meine Buchung verwalten“ checken","Fast-Track-Angebote (52 €): rausgeschmissenes Geld um 13:45 Uhr"],
    warn:"Anquatscher in der Ankunftshalle verlangen 1.500–2.500 ฿ in die Stadt — das Vierfache. Offizielle Taxis stehen UNTEN im Untergeschoss (Automat + Taxameter).", book:[], gmaps:gm("Suvarnabhumi Airport") }
];
