// Bangkok 2026 — Spots (aus Jans recherchierter Karte, 34 Ziele ab Hotel Oakwood Suites Tiwanon)
const HOTEL = {
  name: "Oakwood Suites Tiwanon", lat: 13.8387, lng: 100.5154,
  addr: "229 Krungthep-Nonthaburi Rd, Nonthaburi 11000",
  tel: "+6621499450",
  thai: "โอ๊ควูด สวีทส์ ทิวานนท์ — 229 ถนนกรุงเทพฯ-นนทบุรี บางเขน เมืองนนทบุรี 11000",
  gmaps: "https://www.google.com/maps/search/?api=1&query=Oakwood%20Suites%20Tiwanon%20Bangkok&query_place_id=ChIJRVowhVeb4jAR8Y4UPJncqx4"
};

const CATS = {
  tuer:   { label: "Vor der Tür", color: "#6BCB77" },
  stadt:  { label: "Stadt",       color: "#A78BFA" },
  luxus:  { label: "Luxus",       color: "#E8B04B" },
  party:  { label: "Party",       color: "#4FD8EB" },
  anreise:{ label: "An- & Abreise", color: "#57A8FF" },
  tour:   { label: "Ausflüge",    color: "#F26D9E" }
};

function gm(q){ return "https://www.google.com/maps/search/?api=1&query=" + encodeURIComponent(q); }

const SPOTS = [
  // ————— VOR DER TÜR —————
  { cat:"tuer", name:"Owl Market (Nachtmarkt)", emoji:"🦉", lat:13.8600, lng:100.5150,
    bolt:"10 Min", fare:"70–90 ฿", hours:"Tägl. 17–24 Uhr",
    desc:"Riesiger Nachtmarkt, 4,4 ★ bei 15.700 Bewertungen. Streetfood + Secondhand-Klamotten ab 10 ฿.",
    tips:["Perfekt für den ersten lockeren Abend"], warn:"Gedränge = Handy nach vorn.", book:[], gmaps:gm("Owl Market Nonthaburi") },
  { cat:"tuer", name:"Wat Chaloem Phrakiat", emoji:"🛕", lat:13.8551, lng:100.4869,
    bolt:"12 Min", fare:"80–100 ฿", hours:"Tagsüber", price:"Eintritt frei",
    desc:"Der schönste Tempel der Gegend, direkt am Fluss, chinesisch beeinflusst, Pfauen auf dem Gelände. Fast keine Touristen.",
    tips:["Schultern & Knie bedeckt"], warn:null, book:[], gmaps:gm("Wat Chaloem Phra Kiat Worawihan Nonthaburi") },
  { cat:"tuer", name:"Ko Kret (Flussinsel)", emoji:"🚲", lat:13.9126, lng:100.4750,
    bolt:"20–25 Min bis Wat Sanam Nuea, dann 1 Min Fähre", fare:"Bolt 120–150 ฿ · Fähre 3 ฿ je Richtung", hours:"Fähre 5–21 Uhr · Markt NUR Sa+So ca. 9–17 Uhr", price:"Fahrrad ~40 ฿/Tag · E-Bike ~150 ฿/Std.",
    desc:"Autofreie Flussinsel der Mon-Minderheit, 2 km lang und 1 km breit — in zwei Stunden zu Fuß einmal herum. Töpferdörfer mit offenen Brennöfen, Mon-Streetfood, Tempel. Liegt praktisch vor deiner Haustür und fühlt sich an wie hundert Kilometer weg von Bangkok.",
    tips:["NUR am Wochenende hinfahren — dann zieht sich der Markt über einen Kilometer die Ostseite entlang. Werktags sind die meisten Läden zu und es ist einfach ein stilles Dorf","Dem Bolt-Fahrer einfach „Ko Kret“ oder „Wat Sanam Nuea“ sagen, das kennt jeder. Am Tempel durchlaufen bis zum Pier, Fähre 3 ฿, eine Minute rüber","Fahrrad leihen (~40 ฿) oder laufen — Autos gibt es auf der Insel nicht","Kwan-Aman-Töpfereimuseum tägl. 9–17 Uhr","Vormittags hin, bevor die Sonne knallt"], warn:null, book:[], gmaps:gm("Ko Kret Nonthaburi") },
  { cat:"tuer", name:"Nonthaburi Pier (Expressboot)", emoji:"⛴️", lat:13.8420, lng:100.4930,
    bolt:"10 Min", fare:"70–90 ฿", hours:"Expressboote etwa 6–19 Uhr", price:"orange 18 ฿ · gelb 23 ฿ · rot 32 ฿ (Festpreis je Linie)",
    desc:"Nordende der Chao-Phraya-Expressboote. Für unter 25 Baht den Fluss runter bis zur Altstadt — die schönste Anreise, die Bangkok hat.",
    tips:["Orange Flagge = Standardlinie, hält fast überall, 18 ฿ Festpreis","Gelbe Linie ist schneller (weniger Stopps), 23 ฿","Kombi: Boot hin, abends Bolt zurück — nach 19 Uhr fahren die Expressboote nicht mehr","Das blau beflaggte Touristenboot kostet 60 ฿ pro Fahrt bzw. 200 ฿ Tagespass — brauchst du nicht"], warn:null, book:[], gmaps:gm("Nonthaburi Pier") },
  { cat:"tuer", name:"Health Land Chaengwattana", emoji:"💆", lat:13.9050, lng:100.5250,
    bolt:"20 Min", fare:"120–160 ฿", hours:"Tägl. 9–23 Uhr (letzter Termin je nach Länge früher)", price:"Thai 2 Std. 700 ฿ · mit Kräuterstempel 1.050 ฿ · Aroma-Öl 90 Min 1.200 ฿ / 2 Std. 1.500–1.850 ฿",
    desc:"Deine nächste Filiale, seriöse Kette, private Räume mit Dusche. Zwei Stunden Thai-Massage für 18 €. ACHTUNG: hier gibt es KEIN Ayurveda — nur Thai, Kräuterstempel und Aroma-Öl. Die Ayurveda-Pakete laufen nur in Asoke und Sathorn (eigener Spot).",
    tips:["Die günstige Alternative zum Oriental Spa — gleiche Qualität, ein Bruchteil des Preises","Adresse: 5/55 Moo 3 Chaeng Wattana Rd, Pakkret, Nonthaburi 11120","KEINE Purple-Line-Anbindung — mit Bolt hinfahren, nicht mit der MRT probieren","Tagsüber unter der Woche klappt Walk-in meist; abends und am Wochenende vorher anrufen","Online-Buchung verlangt Konto + Kartenzahlung im Voraus — anrufen ist einfacher"],
    warn:null,
    book:["Anrufen: <a href='tel:+6625733355'>+66 2 573 3355</a> oder <a href='tel:+66863409799'>+66 86 340 9799</a>","Online: <a href='https://reservation.healthlandspa.com' target='_blank' rel='noopener'>reservation.healthlandspa.com</a>","Sagen: Filiale Chaeng Wattana, welche Behandlung, Datum, Uhrzeit, 1 Person"],
    gmaps:gm("Health Land Chaengwattana Pakkret") },
  { cat:"stadt", name:"Health Land Asoke (Ayurveda)", emoji:"🪔", lat:13.7390, lng:100.5615,
    bolt:"45–60 Min", fare:"350–450 ฿", hours:"Tägl. 9–23 Uhr",
    price:"Body Mind & Spirit 3 Std. 4.000 ฿ (~104 €) · Abhyanga 90 Min 1.700 ฿ / 2 Std. 2.000 ฿ · Rejuvenate Me 2,5 Std. 3.200 ฿ · Back Pain 2,5 Std. 2.900 ฿ · Relax Me 2 Std. 2.900 ฿ · Energize Me 2 Std. 2.300 ฿",
    desc:"HIER gibt es die Ayurveda-Pakete — in deiner Nonthaburi-Filiale nicht. „Body Mind & Spirit“ = Blüten-Fußritual + Abhyanga (Ganzkörper-Ölmassage) + Kopf/Nacken/Schultern + Shirodhara (warmes Öl läuft über die Stirn) + Dusche. 3 Stunden für die Hälfte vom Oriental Spa. Adresse: 55/5 Sukhumvit 21 (Asoke), Wattana 10110.",
    tips:["MIT DER BAHN ERREICHBAR: Purple Line ab Yaek Tiwanon → Tao Poon → umsteigen Blue Line → Sukhumvit, Ausgang 3. Kein Bolt nötig, kein Stau.","Terminal 21 liegt direkt daneben — Foodcourt-Abend und Massage am selben Tag verbinden","Sathorn hat exakt dieselben Ayurveda-Pakete zu denselben Preisen","Nach 3 Std. Öl im Haar: erst duschen, dann weiter — Dusche ist im Paket drin"],
    warn:null,
    book:["Anrufen: <a href='tel:+6622611110'>+66 2 261 1110</a> oder <a href='tel:+66863786771'>+66 86 378 6771</a>","Online: <a href='https://reservation.healthlandspa.com' target='_blank' rel='noopener'>reservation.healthlandspa.com</a> — braucht Konto + Kartenzahlung vorab","Filiale Asoke, „Body Mind & Spirit“, Datum, Uhrzeit, 1 Person"],
    gmaps:gm("Health Land Asoke Sukhumvit 21 Bangkok") },
  { cat:"stadt", name:"Chatuchak Weekend Market", emoji:"🧺", lat:13.7999, lng:100.5502,
    bolt:"25 Min", rush:"45 Min", fare:"180–240 ฿", mrt:"Purple → Tao Poon → Blue, ~30–35 Min", hours:"Voll NUR Sa + So 9–18 · Fr 18–24 nur Großhandel · Mi/Do nur Pflanzen",
    desc:"Einer der größten Märkte der Welt — 15.000 Stände. Klamotten, Kunst, Essen, alles.",
    tips:["Früh hin (vor 11), mittags wird's brutal voll & heiß","Feilschen ok: Startpreis −30–40 %","Freitagabend ist NICHT der große Markt: dann läuft nur die Großhandels-Session mit einem Bruchteil der Stände, viele schließen schon gegen 21 Uhr","Alle 27 Sektionen und die 15.000 Stände gibt es ausschließlich Samstag und Sonntag"],
    warn:"Taschendiebe im Gedränge — Rucksack nach vorn, Wertsachen in die Fronttasche.", book:[], gmaps:gm("Chatuchak Weekend Market") },
  { cat:"stadt", name:"Grand Palace + Wat Pho", emoji:"👑", lat:13.7500, lng:100.4913,
    bolt:"35 Min", rush:"65 Min", fare:"230–300 ฿", mrt:"Blue Line bis Sanam Chai, ~50 Min · oder Expressboot ab Nonthaburi Pier", hours:"Palast: Kasse bis 15:30, Gelände bis 16:30 · Wat Pho 8–18:30 · Wat Arun bis 18 Uhr", price:"Palast 500 ฿ · Wat Pho 300 ฿ · Wat Arun 200 ฿",
    desc:"Der Königspalast, der liegende Buddha nebenan und Wat Arun gegenüber am anderen Ufer — drei getrennte Tickets, zusammen 1.000 ฿. Wat Pho hat die Massageschule des Landes: 30 Min ab ~340 ฿, 1 Std. ~520 ฿, direkt auf dem Tempelgelände.",
    tips:["MORGENS hin — die Palastkasse schließt um 15:30, danach kommt keiner mehr rein","Palast-Dresscode ist der strengste des Landes: lange Hose, Oberteil MIT Ärmeln, geschlossene Schuhe oder Sandalen mit Fersenriemen. Shorts, ärmellos, zerrissene Jeans und Flip-Flops werden am Tor abgewiesen — Sarong-Verleih gegen ~200 ฿ Pfand","Das 500-฿-Ticket gilt 7 Tage und deckt Wat Phra Kaew plus das Queen-Sirikit-Textilmuseum mit ab","Wat Arun kostet extra: 5 ฿ Fähre PLUS 200 ฿ Eintritt","Schönste Anreise: Expressboot ab Nonthaburi Pier (18 ฿)"],
    warn:"„Der Palast ist heute geschlossen“-Masche der Tuk-Tuk-Fahrer davor: Er ist täglich offen. Einfach weitergehen.", book:["Ticket am offiziellen Schalter, 500 ฿, bar oder Karte"], gmaps:gm("The Grand Palace Bangkok") },
  { cat:"stadt", name:"Golden Mount (Wat Saket)", emoji:"🌅", lat:13.7539, lng:100.5065,
    bolt:"32 Min", rush:"60 Min", fare:"200–260 ฿", hours:"Tägl. ~7–19 Uhr", price:"~100 ฿",
    desc:"Vergoldeter Chedi auf 80-Meter-Hügel, 340 flache Stufen mit Glocken. Oben: 360°-Blick gratis auf Augenhöhe mit dem 900-฿-Mahanakhon.",
    tips:["16:30 Uhr = tiefe Sonne über der Altstadt","Perfekte Kombi: danach 10 Min rüber in die Mahachai Road zu Thipsamai Pad Thai","Starke Foto-Location (Spiraltreppe!)"],
    warn:"Auch hier die „heute geschlossen“-Masche — Tempel ist täglich offen.", book:[], gmaps:gm("Wat Saket Golden Mount Bangkok") },
  { cat:"stadt", name:"Siam & CentralWorld (Shopping-Meile)", emoji:"🛒", lat:13.7466, lng:100.5347,
    bolt:"45–60 Min", rush:"75 Min", fare:"250–330 ฿", mrt:"Blue Line bis Si Lom → BTS Sala Daeng → 2 Stationen bis Siam · ~60 Min, ~70 ฿", hours:"Täglich 10–22 Uhr",
    desc:"Die eigentliche Shopping-Zone Bangkoks: Siam Paragon, Siam Center, Siam Discovery, MBK und CentralWorld liegen alle nebeneinander und sind per Skywalk verbunden — du läufst trocken und klimatisiert von einer Mall in die nächste. CentralWorld allein hat über 600 Läden.",
    tips:["CentralWorld = Marken zu normalen Preisen (Zara, Uniqlo, Adidas, Muji) · Siam Paragon = Luxus + Gourmet Market im UG · MBK = acht Etagen Handy-Zubehör, Klamotten und Souvenirs zum Feilschen","Der Skywalk verbindet BTS Siam mit BTS Chit Lom — nie auf die Straße runter","Ausweis mitnehmen: ab 2.000 ฿ pro Laden und Tag gibt es VAT-Refund (7 %), Formular an der Kasse verlangen, Stempel am Flughafen","Essen: Pier 21 gibt es hier nicht, dafür der Food Court im Siam Paragon UG und Erawan Tea Room am Erawan-Schrein"],
    warn:"MBK ist die einzige Adresse hier zum Feilschen — in den Malls sind es Festpreise. Und: Kein Elektronik-Schnäppchen bei MBK ohne Garantie-Check.",
    book:[], gmaps:gm("Siam Paragon, Rama I Rd, Pathum Wan, Bangkok") },
  { cat:"tuer", name:"Central WestGate (größte Mall Thailands)", emoji:"🏬", lat:13.8767, lng:100.4110,
    bolt:"25–35 Min", fare:"200–280 ฿", mrt:"Purple Line ab Yaek Tiwanon durchgehend bis Talad Bang Yai — 11 Stationen, KEIN Umsteigen, ~25 Min, ~40 ฿", hours:"Mo–Fr 10–21 · Sa+So 10–22 Uhr",
    desc:"Die flächengrößte Mall Thailands (550.278 m², Platz 8 weltweit) — und sie liegt auf DEINER MRT-Linie, elf Stationen vom Hotel, ohne einmal umzusteigen. Skywalk direkt vom Bahnsteig in die 2. Etage. Über 500 Läden, IKEA, Kino, Eisbahn, Wasserpark Fantasia Lagoon, Tops-Supermarkt.",
    tips:["Der Charakter ist Vorstadt, nicht Luxus: Familien, IKEA, Foodcourt — riesig, aber keine Designermeile","Perfekt als Schlechtwetter-Rückfall: bei Dauerregen bist du in 25 Min drin, ohne Bolt und ohne Umsteigen","Zum Marken-Shoppen ist Siam/CentralWorld die bessere Adresse — hierher gehst du wegen der Nähe","Gegenüber: Big C, HomePro und der Bang-Yai-Obstmarkt"],
    warn:"Unter der Woche schließt sie schon um 21 Uhr, nicht um 22.",
    book:[], gmaps:gm("Central WestGate, 199 Moo 6 Rattanathibet Rd, Bang Yai, Nonthaburi 11140") },
  { cat:"stadt", name:"ICONSIAM (Riesenmall am Fluss)", emoji:"🛍️", lat:13.7264, lng:100.5100,
    bolt:"35 Min", rush:"60 Min", fare:"220–280 ฿", mrt:"BTS Gold Line bis Charoen Nakhon · oder Shuttle-Boot ab Sathorn Pier (~12 ฿)", hours:"Täglich 10–22 Uhr",
    desc:"Bangkoks Mega-Mall am Chao Phraya und nur 750 m zu Fuß vom Oriental Spa. Sieben Etagen von Sook Siam bis Luxusmeile — und der beste Ort, um einen Regennachmittag abzuwarten.",
    tips:["EG: Sook Siam — ein nachgebauter schwimmender Markt mit Ständen aus allen 77 Provinzen, dort essen","1. Stock ICONLUXE: Louis Vuitton, Hermès, Dior, Gucci, Chanel am Fluss","2. Stock: der erste Apple Store Thailands mit Flussterrasse · 4.–5. Stock Restaurants","7. Stock: der größte Starbucks Reserve Thailands, zweistöckig · 6. Stock Tasana-Nakorn-Terrasse mit dem besten Flussblick","Festpreise, kein Feilschen — dafür an der Kasse nach der Steuerrückerstattung für Touristen fragen (VAT Refund)"],
    warn:"Das Shuttle-Boot ab Sathorn Pier ist nicht mehr gratis (~12 ฿).", book:[], gmaps:gm("ICONSIAM, 299 Soi Charoen Nakhon 5, Bangkok") },
  { cat:"stadt", name:"Chinatown (Yaowarat)", emoji:"🏮", lat:13.7398, lng:100.5096,
    bolt:"38 Min", rush:"70 Min", fare:"220–290 ฿", mrt:"Blue Line bis Wat Mangkon — Ausgang mitten im Viertel", hours:"Straße sperrt 17 Uhr, Stände ab ~17:30 bis Mitternacht · MONTAGS ruhen viele Garküchen",
    desc:"Ab 18 Uhr Neon-Schlucht voller Garküchen: Riesengarnelen, Dim Sum, Entennudeln. Mehrere Stände mit Michelin Bib Gourmand. Mit 400 ฿ im Bauch isst du dich quer durch.",
    tips:["Um 17:45 da sein: Stände stehen, Straße ist frei zu laufen. Zwischen 19 und 21 Uhr sind es 30 Min Schlange an den bekannten Ständen","Die Runde ab MRT Wat Mangkon Ausgang 1 nach Osten: Guay Jub Ouan Pochana (Rollnudel-Suppe 50–70 ฿) → Lim Lao Ngow (Fischbällchen, Michelin Bib) → Yaowarat-Toast (25–35 ฿) → Abstecher Soi Nana zu Ba Hao Tian Mi (Nachtisch) → T&K Seafood (Riesengarnelen 200–400 ฿)","300–600 ฿ für einen ganzen Abend durchessen","NUR BARGELD — die wenigsten Stände nehmen Karte","Wat Traimit: 5,5-Tonnen-Buddha aus massivem Gold","Zweitbeste Foto-Kulisse der Stadt (Neon bei Nacht)"],
    warn:"Gedränge = Taschendiebe, Handy nach vorn. Preis vor dem Bestellen fragen, wenn kein Schild. Edelstein-„Einladungen“: weitergehen.", book:[], gmaps:gm("Yaowarat Road Chinatown Bangkok") },
  { cat:"stadt", name:"Wat Mangkon Kamalawat (Laternen-Tempel)", emoji:"🏮", lat:13.7438, lng:100.5106,
    bolt:"38 Min", rush:"70 Min", fare:"220–290 ฿", mrt:"Blue Line bis „Wat Mangkon“, Ausgang 3 — Tempel liegt gegenüber", hours:"Tägl. 8–18 Uhr", price:"Eintritt frei (Spende freiwillig)",
    desc:"Der größte und wichtigste chinesische Tempel Bangkoks (1871), mitten in Chinatown. Die Hallen sind komplett mit tausenden roten Laternen zugehängt — dazu vergoldete Götterfiguren, eine tausendarmige Guanyin aus Sandelholz und Schreine voller Neonlicht. Das ist das Motiv aus deinem Video.",
    tips:["Vormittags 8–10 Uhr: gutes Licht, kaum Leute — nachmittags wird es voll und verräuchert","Schuhe aus vor den Gebetshallen, Schultern + Knie bedeckt (lange Hose!)","Anfahrt ohne Stau: MRT Yaek Tiwanon → Tao Poon umsteigen → Wat Mangkon, ~50 Min, ~50 ฿","700 m zu Fuß zur Yaowarat Road, 1,2 km zum 5,5-Tonnen-Goldbuddha (Wat Traimit) — als eine Runde machbar"],
    warn:"Wer dir VOR dem Tor Räucherstäbchen, „Segen“ oder Eintritt verkaufen will, gehört nicht zum Tempel. Der Eintritt ist frei, Räucherstäbchen gibt es drinnen für ein paar Baht.",
    book:[], gmaps:gm("Wat Mangkon Kamalawat Bangkok") },
  { cat:"stadt", name:"Terminal 21 + Pier-21-Foodcourt", emoji:"🍜", lat:13.7373, lng:100.5600,
    bolt:"35 Min", rush:"65 Min", fare:"230–300 ฿", mrt:"Blue Line bis Sukhumvit (Asok)", hours:"Tägl. 10–22 Uhr", price:"Gerichte ab 50 ฿",
    desc:"Mall mit Themen-Etagen — und im 5. Stock der Preis-Leistungs-König der Stadt: Garküchen-Qualität ab 50 Baht.",
    tips:["Perfekter Start für jeden Sukhumvit-Abend","Geldkarte am Foodcourt-Schalter aufladen, Rest zurücktauschen"], warn:null, book:[], gmaps:gm("Terminal 21 Asok Bangkok") },
  { cat:"stadt", name:"Jodd Fairs Ratchada (Nachtmarkt)", emoji:"🌃", lat:13.7648, lng:100.5688,
    bolt:"30 Min", fare:"200–260 ฿", mrt:"Purple → Tao Poon → Blue bis Thailand Cultural Centre, Ausgang 4 · ~45 Min, ~42 ฿", hours:"Täglich 17–1 Uhr",
    desc:"Der beste Nachtmarkt Bangkoks — rund 800 Stände, Schwerpunkt Essen, dazu Klamotten und Live-Musik. Läuft JEDEN Tag, auch am Ankunftsabend. Gut alleine zu machen.",
    tips:["Vor 19 Uhr da sein: dann sind die Tische frei und die Leng-Saap-Schlange kurz","Leng Saap (der Schweine-Rückgrat-Turm ab 180 ฿) ist DAS Foto-Gericht","Abendessen für 200–400 ฿ quer durch die Stände","Direkt nebenan liegt der Train Night Market Ratchada — zwei Märkte an einer Station"],
    warn:"Die MRT fährt nur bis Mitternacht, die Stände bis 1 Uhr — wer länger bleibt, braucht ein Bolt. Und: Jodd Fairs Rama 9 gibt es seit Januar 2025 NICHT mehr, im Navi immer „Jodd Fairs Ratchada“ eingeben.",
    book:[], gmaps:gm("Jodd Fairs Ratchada, 129 Ratchadaphisek Rd, Din Daeng, Bangkok") },
  { cat:"stadt", name:"Train Night Market Ratchada (Vintage)", emoji:"🚂", lat:13.7660, lng:100.5710,
    bolt:"30 Min", fare:"200–260 ฿", mrt:"wie Jodd Fairs: Thailand Cultural Centre, hinter dem Esplanade", hours:"Täglich 17–1 Uhr",
    desc:"Der Regenbogen-Zeltmarkt ist am 27.03.2026 nach fünf Jahren Pause wieder aufgemacht: Vintage-Händler, Container-Bars, Livebands. Anderes Erlebnis als Jodd Fairs, gleiche MRT-Station.",
    tips:["Die Foto-Perspektive: von oben aus dem Parkhaus des Esplanade auf das Zeltmeer","Lässt sich mit Jodd Fairs zu einem Abend verbinden — 5 Min zu Fuß"],
    warn:null, book:[], gmaps:gm("Train Night Market Ratchada, Esplanade, Bangkok") },
  { cat:"stadt", name:"Klong-Tour im Longtail (Thonburi)", emoji:"🛶", lat:13.7437, lng:100.4889,
    bolt:"35 Min", fare:"230–300 ฿", price:"Privatboot 1.500–2.500 ฿",
    desc:"Privates Longtail-Boot durch die Kanäle von Thonburi bei Sonnenaufgang. Um 7 Uhr früh gehört dir die Stadt allein.",
    tips:["Start ab Sathorn/Oriental Pier oder Wat Arun","Preis + Dauer VOR dem Einsteigen festmachen"],
    warn:"Nur an offiziellen Piers buchen — nicht bei Anquatschern am Straßenrand.", book:["Am Pier: Route zeigen lassen","1 Std. = fair bei 1.000–1.500 ฿"], gmaps:gm("Wat Arun Bangkok") },
  { cat:"stadt", name:"Bang Krachao (grüne Lunge)", emoji:"🌿", lat:13.6784, lng:100.5620,
    bolt:"45 Min + Boot", fare:"300–380 ฿", price:"Fahrrad ~100 ฿, Boot 10 ฿",
    desc:"Flussschleife voller Dschungel und Holzstege mitten in der Stadt. Halber Tag Radfahren, kostet fast nichts.",
    tips:["Früh los — mittags brütend heiß"], warn:null, book:[], gmaps:gm("Bang Krachao Bangkok") },
  { cat:"tour", name:"Ayutthaya — selbst per Zug", emoji:"🏛️", lat:14.3532, lng:100.5689,
    bolt:"Zug ~1 Std. ab Krung Thep Aphiwat (Bang Sue)", fare:"3. Klasse Rapid/Express ~70 ฿ · klimatisierte 2. Klasse 65–345 ฿", hours:"Ruinen tägl. 8–18 Uhr · hin: Rapid 111 7:50 oder Express 75 8:45 · zurück: Rapid 112 16:04 oder Rapid 136 16:41", price:"Alles zusammen ~600 ฿ — eine geführte Tour kostet 29–37 €",
    desc:"Alte Königsstadt, 71 km nördlich: Tempelruinen zum Reinlaufen, beeindruckender als der Grand Palace und ein Bruchteil der Touristen. Ab Krung Thep Aphiwat (Bang Sue) fahren 16 Fernzüge am Tag, MRT-Blue-Line-Anschluss von deinem Hotel.",
    tips:["Rechnung: Zug ~140 ฿ hin+zurück, Roller 250 ฿, Sammelticket 220 ฿ = gut 15 € statt 30+ € für eine Tour — und du hängst an keiner Gruppe","Ticket am Schalter kaufen, Rückfahrt gleich mit. Fahrplanzeiten am Schalter bestätigen lassen, in Thailand verschieben die sich gern","Sammelticket 220 ฿ gilt für sechs Tempel — lohnt sich ab drei","Wat Mahathat: Buddha-Kopf im Baum","Ayothaya Floating Market: reine Touri-Show — kannst du dranhängen, kein Muss"],
    warn:"Tuk-Tuk statt Roller? Pauschale VOR der Fahrt festmachen (4 Std. ~ 800–1.000 ฿).", book:["MRT bis Krung Thep Aphiwat (Bang Sue)","Schalter: Zug nach Ayutthaya, ~50 ฿","Vor Ort Roller/Tuk-Tuk, abends zurück"], gmaps:gm("Ayutthaya Historical Park") },
  { cat:"tour", name:"Ancient City (Muang Boran)", emoji:"🛕", lat:13.5394, lng:100.6231,
    bolt:"45–60 Min", fare:"400–500 ฿", mrt:"BTS Sukhumvit-Linie bis Kheha (Endstation), dann Songthaew 36 für 10–20 ฿ · samstags gratis Shuttle ab Kheha", hours:"Täglich 9–19 Uhr, Kasse bis 18 Uhr", price:"700 ฿ am Tor · online über Klook oft ~350 ฿",
    desc:"Das größte Freilichtmuseum der Welt: über 100 nachgebaute Tempel, Paläste und Holzhäuser aus ganz Thailand auf 80 Hektar Park — und fast menschenleer. Du fährst mit dem Fahrrad zwischen schwimmenden Pavillons, Ruinennachbauten und einem See mit Holzstegen umher. Der fotogenste Ort im Großraum Bangkok, den kaum ein Tourist kennt.",
    tips:["Vorher online kaufen — am Tor 700 ฿, über Klook oft die Hälfte","Fahrrad ~100 ฿ für den ganzen Tag; die kostenlose Tram fährt 10, 13, 15 und 17 Uhr, aber DAS MUSST DU BEIM TICKETKAUF SAGEN","Rechne mit 3–4 Std., mit dem Erawan-Museum 5–6","Kein Englisch nötig — du läufst und radelst einfach, es ist ein Park","Früh hin: vormittags ist es kühler und das Licht besser","Nebenan das Erawan-Museum: ein 43 m hoher dreiköpfiger Elefant aus Kupfer, in dem man hochsteigen kann"],
    warn:"Weit draußen in Samut Prakan — mit der Bahn 75–90 Min. Lieber morgens per Bolt hin (45–60 Min) und nachmittags entspannt per BTS zurück.",
    book:["Klook oder GetYourGuide: „Ancient City“ — Kombiticket mit Erawan-Museum lohnt","Am Tor geht auch ohne Voranmeldung"], site:"https://www.muangboranmuseum.com/en/", gmaps:gm("Ancient City Muang Boran Samut Prakan") },
  { cat:"tour", name:"Bangkok Elephant Park (ethisch)", emoji:"🐘", lat:13.8300, lng:100.8800,
    bolt:"~1–1,5 Std. mit Bolt (Rushhour mehr)", fare:"~600–900 ฿/Strecke", hours:"Park tägl. 9–17 Uhr · Halbtag OHNE Transfer: 9–12 oder 13–16:30 Uhr", price:"GYG ~43–55 € (Halbtag)",
    desc:"Ethische Elefantenpflege, 47 Suwinthawong Rd, Krathum Rai, Nong Chok, Bangkok 10530 (NICHT Chachoengsao — Ostrand von Bangkok, ~50 km ab Hotel), 4,8 ★ (1.000+): füttern, Schlamm-Spa, baden — kein Reiten, keine Shows. Thai-Buffet inklusive. Dein Guide-frei-Trick: Die Option OHNE Transfer buchen und selbst mit Bolt hin — empfehlen sogar die Bewertungen.",
    tips:["Ohne-Transfer-Option = günstiger + du bestimmst das Tempo","Park stellt Outfit, Hut UND Handtuch — du brauchst nur Badehose + trockene Wechselsachen für die Heimfahrt","Vormittags-Slot nehmen — nachmittags Regenzeit-Schauer","Direkt beim Park (bangkokelephant.com, FareHarbor): 2.200 ฿ ≈ 58 € — vor dem Buchen mit dem GYG-Preis vergleichen","Ablauf 9–12: Welcome Drink, Elefantenkunde, Kräuterinhalator basteln, füttern, Waldspaziergang, Schlamm-Spa, baden, Thai-Lunchbox","Tel. Park +66 90 920 5885"],
    warn:"Abgelegen: Für den Rückweg den Bolt-Fahrer warten lassen (Festpreis vereinbaren) oder notfalls doch die Transfer-Option nehmen — draußen fahren wenige Autos.",
    book:["GetYourGuide: „Bangkok Elephant Park“ → Halbtag ohne Transfer","Bis 24 h vorher kostenlos stornierbar"], site:"https://www.getyourguide.com/de-de/bangkok-l169/bangkok-ethische-elefanten-tour-mit-hoteltransfer-t740092/", gmaps:gm("Bangkok Elephant Park, 47 Suwinthawong Rd, Krathum Rai, Nong Chok, Bangkok 10530") },
  { cat:"tour", name:"Chao-Phraya Dinner-Cruise (5 Sterne)", emoji:"🛳️", lat:13.7045, lng:100.5028,
    bolt:"40 Min bis Asiatique", fare:"260–340 ฿", hours:"Tägl., Slots ab 18 Uhr, Hauptfahrt 20–22 Uhr, Check-in ~19:45", price:"ab ~26 € · mit Dinner 34–52 €",
    desc:"Die neueste Luxus-Cruise auf dem Fluss: ab Asiatique The Riverfront vorbei an ICONSIAM, Wat Arun und Grand Palace im Nachtlicht. Braucht keinen Guide — ist eh nur ein Ticket: buchen, hingehen, einsteigen.",
    tips:["18-Uhr-Slot = Sonnenuntergang + Nachtlichter in einem","Als Solo top: Deck-Platz statt Tisch, Kamera mitnehmen","Kombinierbar: vorher Asiatique-Nachtmarkt, danach Bolt heim"],
    warn:"Nur online mit Datum/Slot buchen — Ticketverkäufer am Pier-Vorplatz sind teurer oder falsch.",
    book:["GetYourGuide: Datum + Uhrzeit wählen","QR-Ticket aufs Handy, Check-in Asiatique Pier"], site:"https://www.getyourguide.com/de-de/bangkok-l169/bangkok-die-neueste-luxuriose-5-sterne-kreuzfahrt-auf-dem-chao-phraya-in-bangkok-t960991/", gmaps:gm("Asiatique The Riverfront Bangkok") },
  { cat:"stadt", name:"Mahanakhon SkyWalk", emoji:"🏙️", lat:13.7233, lng:100.5285,
    bolt:"38 Min", fare:"250–320 ฿", mrt:"BTS Chong Nonsi, Ausgang 3 — der Turm steht direkt über der Station", hours:"SkyWalk tägl. 10–19 Uhr, letzter Einlass 18:30 (Innendeck länger)", price:"tagsüber 880–1.000 ฿ · Sonnenuntergang 1.080–1.200 ฿",
    desc:"Der höchste Aussichtspunkt der Stadt: Innendeck im 74. Stock, offenes Dach im 78. und der berühmte Glasboden auf 310 m. Deutlich mehr Erlebnis als die Sky Bar — und du zahlst dort für EIN Getränk fast so viel.",
    tips:["Sonnenuntergangs-Slot nehmen und 45–60 Min vorher da sein: Stadt bei Tag, Sonnenuntergang und Lichtermeer in einem Besuch. Ende August/Anfang September geht die Sonne um 18:26–18:32 unter","Online vorab buchen ist günstiger als an der Kasse und die Sonnenuntergangs-Slots sind schnell weg","Kein Dresscode, Rucksack erlaubt — anders als in der Sky Bar","Gleich über der BTS-Station, überdachter Zugang"],
    warn:"Bei Regen oder Sturm sperren sie das Außendeck und den Glasboden — Geld gibt es nicht zurück, nur eine Umbuchung. In der Regenzeit erst den Himmel anschauen, dann buchen.", book:[], gmaps:gm("King Power Mahanakhon Bangkok") },

  // ————— LUXUS & ABEND —————
  { cat:"luxus", name:"Oriental Spa (Mandarin Oriental)", emoji:"🧖", lat:13.7237, lng:100.5147,
    bolt:"40–45 Min", fare:"250–330 ฿", price:"Moringa 2 Std. = 6.900 ฿ + 17 % (~211 €)", hours:"DEIN TERMIN: So 30.08., 10:30 Uhr ✓",
    desc:"GEBUCHT! Bis 60 Min vorher ankommen: Sauna, Dampfbad & Jacuzzi im Wellness Centre sind inklusive. Bestätigungs-Nr. in Meine Reisedaten.",
    tips:["DEIN WEG: Bolt zum Mandarin Oriental Hotel (Stadtseite) → gratis Hotelboot ab Hotel-Pier über den Fluss zum Spa","Beim Boot einfach sagen: „Oriental Spa, appointment 10:30“","Danach: ICONSIAM nur 750 m zu Fuß","Storno nur bis 24 h vorher — sonst 100 % fällig","Payment-Link kommt 2 Tage vorher per Mail (28.08.)"],
    warn:null, book:["mandarinoriental.com/bangkok → Spa → Termin buchen"], gmaps:gm("Mandarin Oriental Bangkok Hotel") },
  { cat:"luxus", name:"Sky Bar (Lebua) — 1 Drink & Foto", emoji:"🥂", lat:13.7218, lng:100.5164,
    bolt:"40 Min", fare:"250–330 ฿", hours:"Täglich 17:00–00:30, letzte Bestellung 00:15", price:"Kein Eintritt, aber 1 Getränk Pflicht · Mocktail 600–800 ฿ + 17 % = ~700–950 ฿",
    desc:"Der Hangover-2-Rooftop im 64. Stock des State Tower, 247 m über der Stadt. Aussicht top, Preise Touristenfalle. Einmal hin, ein Getränk, Foto, weiter. Nur Stehplätze am runden Bartresen, keine Reservierung möglich — walk-in.",
    tips:["Dresscode wird am Aufzug durchgesetzt: Kragenhemd oder Polo, lange Hose, geschlossene Schuhe. T-Shirt, Shorts, ärmellos, Sandalen und Sneaker = abgewiesen","RUCKSÄCKE, Einkaufstüten und Gepäck sind oben verboten — und es gibt KEINE Aufbewahrung. Vorher ins Hotel damit","Es gibt kein Essen, nur Getränke","Fotos sind erlaubt, Videos nicht","Danach oder als Alternative: Octave in Thonglor, entspannter und überdacht"], warn:"Bei Regen schließt die offene Plattform sofort — in der Regenzeit immer einen Plan B haben.", book:[], gmaps:gm("Sky Bar Lebua Bangkok") },
  { cat:"luxus", name:"Octave Rooftop (Thonglor)", emoji:"🌆", lat:13.7247, lng:100.5827,
    bolt:"45 Min", fare:"280–360 ฿", hours:"17–2 Uhr", price:"Mindestverzehr ~1.800 ฿",
    desc:"Das bessere Rooftop: 360°, DJ, entspannter als Sky Bar. Auf dem Marriott Thonglor.",
    tips:["Zum Sonnenuntergang kommen, oben anfangen"], warn:null, book:[], gmaps:gm("Octave Rooftop Lounge Bangkok") },
  { cat:"luxus", name:"Saxophone Pub (Livejazz)", emoji:"🎷", lat:13.7629, lng:100.5372,
    bolt:"28 Min", fare:"180–240 ฿", hours:"Tägl. abends, Musik ab ~20:30",
    desc:"Livejazz & Blues seit den Achtzigern am Victory Monument. Gemischtes Publikum, Tresen-Atmosphäre — da will keiner was von dir.",
    tips:["Guter „entspannter Abend“-Joker"], warn:null, book:[], gmaps:gm("Saxophone Pub Bangkok") },
  { cat:"party", name:"Sukhumvit Soi 11", emoji:"🍹", lat:13.7415, lng:100.5555,
    bolt:"35 Min", rush:"70 Min", fare:"230–300 ฿",
    desc:"Die kompakteste Ausgehstraße: 800 m Bars, Rooftops, Streetfood. Highlight: Havana Social — Speakeasy mit Eingang durch eine Telefonzelle.",
    tips:["Havana Social: Speakeasy mit Telefonzellen-Eingang, Mocktails stehen auf der Karte","Ab hier 10 Min Bolt nach Thonglor"],
    warn:"Je kleiner die Soi-Nummer, desto mehr will dir jemand was verkaufen. Nie mitgehen, wenn dich jemand „mitnimmt“ — Provisions-Masche.", book:[], gmaps:gm("Sukhumvit Soi 11 Bangkok") },
  { cat:"anreise", name:"Suvarnabhumi Airport (BKK)", emoji:"✈️", lat:13.6900, lng:100.7501,
    bolt:"45–60 Min", fare:"~600 ฿ + Maut", hours:"Rückflug 6.9.: 22:55 Uhr — 3 Std. vorher da sein",
    desc:"Dein Flughafen. Ankunft 28.8. um 13:45: TDAC-QR + Pass bereithalten, 20–40 Min Immigration, Gepäck, raus.",
    tips:["Transfer ist in deiner Buchung INKLUSIVE — Abholzeit 24 h vorher in „Meine Buchung verwalten“ checken","Fast-Track-Angebote (52 €): rausgeschmissenes Geld um 13:45 Uhr"],
    warn:"Anquatscher in der Ankunftshalle verlangen 1.500–2.500 ฿ in die Stadt — das Vierfache. Offizielle Taxis stehen UNTEN im Untergeschoss (Automat + Taxameter).", book:[], gmaps:gm("Suvarnabhumi Airport") }
];
